<a href="https://colab.research.google.com/github/Vaibhavsj75/Diamond-Problem-/blob/main/Untitled21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NAME: Vaibhav Jadhav
ROLL_NO: 13211
BATCH: B1

In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array([2, 3, 5, 7, 10])

In [6]:
print(x)

[ 2  3  5  7 10]


In [7]:
type(x)

numpy.ndarray

In [8]:
x=np.array(([2,5,7,10]),dtype="float")

In [9]:
type(x)

numpy.ndarray

In [10]:
x = np.zeros((3, 4))

In [11]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
x=np.ones((3,4))

In [13]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
x = np.full((3, 4), 9)

In [16]:

print(x)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [17]:
x=np.eye(3,3)

In [18]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
x = np.arange(2, 10, 3)

In [20]:
print(x)

[2 5 8]


In [21]:
x = np.linspace(7, 10, 10)

In [22]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
