<a href="https://colab.research.google.com/github/Vaibhavsj75/Diamond-Problem-/blob/main/Practical_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NAME: Vaibhav Jadhav
ROLL_NO: 13211
BATCH: B1

In [1]:
import numpy as np

In [2]:
x= np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [3]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print("value at [0][0] and [0][1] : ",x[0:1,0:2])

value at [0][0] and [0][1] :  [[0 1]]


In [5]:
print("value at[1][0] :",x[1:2, 0:1])

value at[1][0] : [[4]]


In [6]:
print("value at[1][1],[1,2],[1,3] :",x[1:2,1:4])

value at[1][1],[1,2],[1,3] : [[5 6 7]]


In [7]:
print(x[1:3,1:4])

[[ 5  6  7]
 [ 9 10 11]]


In [8]:
y=np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23],[24,25,26,27]])

In [9]:
print(y)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [10]:
print("value as 35,36,43,47:",y[1:3,1:3])

value as 35,36,43,47: [[17 18]
 [21 22]]


In [11]:
print(y[2: ,1: ])

[[21 22 23]
 [25 26 27]]
